service:
  project-path: github.com/kubesaw/ksctl
  prepare: # see https://github.com/golangci/golangci/wiki/Configuration#config-directives
  - make generate

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m


linters:
  enable:
  - gocyclo
  - gofmt
  - revive
  - misspell
  - gosec
  - gosimple
  - staticcheck
  presets: # groups of linters. See https://golangci-lint.run/usage/linters/
  - bugs
  - unused
  disable:
  - contextcheck # too many false-positives
  - noctx # not needed

# all available settings of specific linters
linters-settings:
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: true
  revive:
    rules:
    - name: dot-imports
      disabled: true
