apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: host-roles
objects:

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: restart-deployment
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: view-secrets
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: edit-secrets
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: add-space-users
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "spacebindings"
    verbs:
    - "get"
    - "list"
    - "create"
    - "delete"
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "masteruserrecords"
    - "nstemplatetiers"
    - "spaces"
    verbs:
    - "get"
    - "list"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: approve-user
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "usersignups"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ban-user
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "bannedusers"
    verbs:
    - "get"
    - "list"
    - "create"
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "usersignups"
    verbs:
    - "get"
    - "list"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: deactivate-user
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "usersignups"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: promote-user
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "masteruserrecords"
    - "spaces"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "nstemplatetiers"
    - "usertiers"
    verbs:
    - "get"
    - "list"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: disable-user
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "masteruserrecords"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: gdpr-delete
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "usersignups"
    verbs:
    - "get"
    - "list"
    - "delete"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: retarget-user
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "usersignups"
    verbs:
    - "get"
    - "list"
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "spaces"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: create-social-event
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "socialevents"
    verbs:
    - "create"
    - "get"
    - "list"
    - "delete"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: enable-feature
    labels:
      provider: sandbox-sre
  rules:
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "toolchainconfigs"
    verbs:
    - "get"
    - "list"
  - apiGroups:
    - toolchain.dev.openshift.com
    resources:
    - "spaces"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"
